# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 22:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170630_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 30, 22, 35, 31, 349826, tzinfo=utc)),
        ),
    ]
